# Based on: https://github.com/OneBusAway/onebusaway-android/blob/master/.travis.yml

language: android
jdk: oraclejdk8

# Turn off caching to avoid any caching problems
cache: false

# Don't use the Travis Container-Based Infrastructure - See #476
sudo: true
env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=24.0.1
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-24

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    # Create and start emulator
    - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

script:
  - android-wait-for-emulator
  - adb devices
